### PR TITLE
Magnetic card reader controllable lights

### PR DESCRIPTION
**Pull request by cadergator10**
This update to the mod adds two new functions to the mag reader: swipeIndicator(bool) and setLightState(int)
swipeIndicator takes in a bool and sets whether the magreader automatically controlls the lights. If true, it does, if false, it doesn't. If set to false, then setLightState is useable.
setLightState takes in an integer from 1 to 4. 1 is no lights, 2 is red, 3 is yellow, and 4 is green. This only works if swipeIndicator is false.

### CODE REVIEW

**Comment by cadergator10** [comment]
I finally figured out how to get it to change the light, and through some testing, it works!

**Comment by cadergator10** [comment]
In absence of any activity on this, I added a few more textures for the magnetic card reader to allow for lights to be on at the same time. Command also was changed so 0 is idle, 1 is red, 2 is yellow, and 4 is green.

**Comment by cadergator10** [comment]
When will this be pulled into main repo

**Comment by cadergator10** [comment]
Bumping pull request due to lots of inactivity to see if you have returned

**Comment by ben-mkiv** [comment]
just wanted to add that we now have an "official" build with your changes, thanks for the contribution :)
https://www.curseforge.com/minecraft/mc-mods/opensecurity/files/4069429

**Pull request merged**
