### PR TITLE
Port to 1.12.2

### PR DESCRIPTION
**Pull request by drzpk**
I've made a port to 1.12.2. Most of the stuff works (I haven't tested everything yet). Only recipes are yet to be ported.

**Note:** because of switching to Forge capabilities and normalizing some block names there may be compatibility issues with worlds from 1.10.2.

### CODE REVIEW

**Comment by CaitlynMainer** [comment]
Thanks, everything looks great except I get the following error in ContentRegistry:
```Description	Resource	Path	Location	Type

The method registerTileEntity(Class<? extends TileEntity>, String) in the type GameRegistry is not 

applicable for the arguments (Class<capture#1-of ? extends TileEntity>, ResourceLocation)
	
ContentRegistry.java	/OpenSecurity/src/main/java/pcl/opensecurity/common	line 117
```

I'll take a look after work if you've not been able to figure it out by then.

**Comment by drzpk** [comment]
That's weird, I had tested everything before I made the pull request and there was no such error. Besides, 
 the _GameRegistry_ class should contain these two methods (Forge 1.12.2-14.23.4.2705):
```java
public static void registerTileEntity(Class<? extends TileEntity> tileEntityClass, String key);
public static void registerTileEntity(Class<? extends TileEntity> tileEntityClass, ResourceLocation key);
```
How is it possible that it doesn't have the latter in your environment?

**Comment by CaitlynMainer** [comment]
No idea I reverted the commit I made to resolve conflicts with you pr,
merged and pulled ran setupDecompWorkspace eclipse again and only that line
throws an error.

**Comment by CaitlynMainer** [comment]
Ok, it seems that Eclipse has decided to hold on to the old ForgeSrc dep, and won't let it go. 14.23.2.2631 doesn't have that method.

**Pull request merged**
