### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by 493505110**

### CODE REVIEW

**Comment by mckuhei** [comment]
`scanner ` 应该翻译成`扫描器`
`scanner` should be translate to `扫描器`

**Comment by 493505110** [comment]
OK

**Comment by ben-mkiv** [comment]
is one of you able to also translate the missing ones?

**Comment by mckuhei** [comment]
Sorry,I‘m afraid not,Because i'm not good at in English.

**Comment by CoolCat467** [comment]
I built a script to automatically translate json-based files with google translate. Yes, machine translations tend to be bad, but at least it would have the base idea there and people who use the language(s) can fix any problems.

**Comment by mckuhei** [comment]
> I built a script to automatically translate json-based files with google translate. Yes, machine translations tend to be bad, but at least it would have the base idea there and people who use the language(s) can fix any problems.

plz no, Google will translate `redstone` into `雷石东` instead of `红石`

**Comment by CoolCat467** [comment]
That's what I'm saying. Machine translations tend to be bad, but at least the base of it would be there.

**Pull request merged**
